// Fictional profiles deliberately include counterexamples to title and keyword matching.
export const peopleProfiles = [
  [
    "Software engineer",
    "On-site",
    "TypeScript, SQL, embedded systems",
    "Writes software for laboratory robots. Every change must be tested on equipment inside the lab; the code cannot leave the building.",
  ],
  [
    "Software engineer",
    "Remote",
    "TypeScript, Postgres, customer discovery",
    "Builds internal tools for a team spread across six time zones. Replaced status meetings with written proposals and recorded demos.",
  ],
  [
    "Registered nurse",
    "Remote",
    "Triage, patient education, care coordination",
    "Reviews patient messages and teaches families to use home monitoring devices by video. No ward rounds or bedside duties.",
  ],
  [
    "Registered nurse",
    "On-site",
    "Emergency care, triage, clinical practice",
    "Works emergency-department shifts and stabilizes patients before transfer. Physical assessments are a central part of every shift.",
  ],
  [
    "Head chef",
    "Remote",
    "Recipe development, teaching, food costing",
    "Left restaurant service to develop recipes in a home test kitchen. Teaches cooking classes over video and writes guides for beginners.",
  ],
  [
    "Head chef",
    "On-site",
    "Kitchen operations, team leadership, food safety",
    "Leads dinner service for a busy restaurant. Has to taste dishes, supervise the pass, and train new cooks during their shifts.",
  ],
  [
    "Customer support specialist",
    "Remote",
    "SQL, incident analysis, documentation",
    "Investigates invoice discrepancies by joining billing tables and checking query plans. Explains the cause to customers without database jargon.",
  ],
  [
    "Data analyst",
    "Hybrid",
    "Spreadsheets, dashboards, survey design",
    "Works entirely in spreadsheets and a drag-and-drop reporting tool. Has never written a database query; SQL is on next year's learning plan.",
  ],
  [
    "School teacher",
    "Hybrid",
    "Curriculum design, facilitation, Python",
    "Built a small grading tool and taught colleagues how to use it. Turns abstract ideas into practical exercises for people with no technical background.",
  ],
  [
    "Machine learning researcher",
    "Remote",
    "Python, statistics, experimental design",
    "Designs evaluation methods and reads research papers. Prefers specialist audiences and explicitly avoids customer-facing teaching or sales work.",
  ],
  [
    "Implementation consultant",
    "Remote",
    "APIs, onboarding, workflow design",
    "Helps family-owned shops adopt inventory software. Translates error messages into plain language and walks owners through setup without assuming technical knowledge.",
  ],
  [
    "Sales director",
    "Hybrid",
    "Enterprise sales, negotiation, account strategy",
    "Sells complex software but delegates every technical explanation to a solutions engineer. Focuses on contracts and procurement rather than product training.",
  ],
  [
    "Operations coordinator",
    "Remote",
    "Process design, vendor management, budgeting",
    "Joined a four-person company before it had a product. Built the first invoicing process and handled whatever broke, without a manager or a playbook.",
  ],
  [
    "Product manager",
    "Hybrid",
    "Roadmaps, stakeholder management, research",
    "Has only worked at established banks with dedicated research, legal, and delivery teams. Advises a startup at weekend events but has never worked inside one.",
  ],
  [
    "Museum archivist",
    "Hybrid",
    "Cataloguing, OCR, data quality",
    "Converted handwritten accession records into a searchable collection. Reconciled conflicting dates and taught volunteers how to spot unreliable metadata.",
  ],
  [
    "Field service technician",
    "On-site",
    "Diagnostics, electronics, training",
    "Travels to repair industrial printers. Explains faults calmly to shop owners and teaches them preventive maintenance, but repairs require touching the equipment.",
  ],
  [
    "Technical writer",
    "Remote",
    "API documentation, usability testing, accessibility",
    "Rewrites developer documentation for first-time users. Tests every walkthrough with people who have never used a command line.",
  ],
  [
    "Technical writer",
    "On-site",
    "Documentation, mechanical drawings, compliance",
    "Documents classified hardware in a secure facility. Cannot access the material outside the office despite doing most of the writing at a desk.",
  ],
  [
    "Community organizer",
    "Hybrid",
    "Facilitation, mediation, multilingual workshops",
    "Coordinates volunteers who disagree about priorities. Gets quiet participants heard and turns messy discussions into written decisions and assigned next steps.",
  ],
  [
    "Finance manager",
    "Remote",
    "Forecasting, SQL, risk analysis",
    "Built self-serve finance reports with database queries. Left a company after its first acquisition and is comfortable doing hands-on work without an analyst team.",
  ],
  [
    "Recruiter",
    "Remote",
    "Technical recruiting, interviewing, coordination",
    "Recruits SQL developers and data engineers. Recognizes the terminology on a CV but does not write code or query databases personally.",
  ],
  [
    "Accessibility specialist",
    "Remote",
    "Assistive technology, user research, web standards",
    "Pairs with screen-reader users to uncover barriers that automated audits miss. Can explain a browser bug to both engineers and a frustrated customer.",
  ],
  [
    "Logistics planner",
    "Hybrid",
    "Routing, spreadsheets, incident response",
    "Rerouted deliveries during a warehouse closure using incomplete information. Kept drivers informed with short updates and documented assumptions as conditions changed.",
  ],
  [
    "Interior designer",
    "Hybrid",
    "CAD, client interviews, spatial planning",
    "Produces drawings and consults by video, but must visit sites twice a week to measure rooms. Can do part of the job from home, not the entire role.",
  ],
] as const;

export const careerNotes = [
  "Mentors career changers in a weekly evening session.",
  "Prefers a clear written brief and uninterrupted focus time.",
  "Recently coordinated a project across three countries.",
  "Likes small experiments before committing to a big rollout.",
  "Keeps detailed handover notes so another person can pick up the work.",
  "Has led small projects but does not want a people-management role.",
  "Comfortable admitting uncertainty and asking for missing context.",
  "Available for short projects; not currently looking for a permanent role.",
  "Can take a permanent role but cannot travel overnight.",
  "Enjoys coaching individuals more than presenting to a large audience.",
  "Prefers scheduled calls over frequent last-minute interruptions.",
  "Has worked with both public-sector and private-sector clients.",
] as const;
