// Notes change the meaning of an identical reading; a threshold alone is insufficient.
export const sensorScenarios = [
  [
    "Vaccine refrigerator",
    9,
    45,
    92,
    "Online",
    "Contents must stay between 2°C and 8°C. Door was closed 40 minutes ago; temperature has continued climbing.",
  ],
  [
    "Vaccine refrigerator",
    5,
    46,
    88,
    "Online",
    "Contents must stay between 2°C and 8°C. Previously reported overheating, but the compressor was repaired and readings have been stable for six hours.",
  ],
  [
    "Empty test refrigerator",
    14,
    44,
    97,
    "Maintenance",
    "Unit is empty and disconnected for a scheduled defrost. No temperature-sensitive stock is inside; warming is expected until the test ends.",
  ],
  [
    "Server inlet",
    36,
    31,
    91,
    "Online",
    "Recommended inlet range is 18–27°C. Three adjacent probes agree; the cooling fan stopped and production traffic is still running.",
  ],
  [
    "Kiln exhaust",
    48,
    12,
    85,
    "Online",
    "Normal operating range for this exhaust probe is 40–60°C during firing. Current cycle is proceeding as scheduled.",
  ],
  [
    "Freezer aisle",
    -9,
    64,
    78,
    "Online",
    "Frozen stock requires -18°C or colder. The aisle feels cold, but this is the third consecutive reading above the storage limit.",
  ],
  [
    "Greenhouse",
    31,
    78,
    72,
    "Online",
    "Tropical seedlings are in a planned warm, humid propagation cycle. Target is 28–33°C and 70–85% humidity.",
  ],
  [
    "Archive storage",
    23,
    82,
    81,
    "Online",
    "Paper records require 35–55% humidity. A pipe leaked overnight and the dehumidifier tank is full.",
  ],
  [
    "Archive storage",
    23,
    49,
    84,
    "Online",
    "A previous humidity alarm has cleared. The leak is repaired, fans are running, and all nearby probes have returned to target.",
  ],
  [
    "Loading bay",
    18,
    51,
    7,
    "Online",
    "Runs entirely on its battery. Replacement is not scheduled for another week; a shutdown would leave the bay unmonitored.",
  ],
  [
    "Office desk",
    22,
    43,
    6,
    "Online",
    "Plugged into mains power and charging. The internal battery was deliberately drained during a capacity test; no interruption is expected.",
  ],
  [
    "Flood pump room",
    19,
    67,
    64,
    "Offline",
    "Unexpectedly stopped transmitting during heavy rainfall. This is the only probe monitoring the sump, and no technician is on site.",
  ],
  [
    "Workshop spare",
    21,
    48,
    61,
    "Offline",
    "Decommissioned spare with no assigned monitoring duty. Its replacement is online and has already passed the handover check.",
  ],
  [
    "Calibration bench",
    52,
    18,
    94,
    "Maintenance",
    "Technician is applying a known heat source to verify the upper measurement range. Probe is disconnected from operational alarms.",
  ],
  [
    "Water tank",
    25,
    63,
    79,
    "Online",
    "Temperature jumped 20 degrees in one sample; two adjacent probes remain at 5°C. Loose connector found, so verify this sensor before acting on the reading.",
  ],
  [
    "Nursery incubator",
    33,
    58,
    89,
    "Online",
    "Target temperature is 35–37°C. Reading has fallen steadily for 25 minutes despite the heater being commanded on.",
  ],
  [
    "Cold-storage doorway",
    11,
    61,
    83,
    "Online",
    "Brief rise while a delivery passed through. Door is now closed and temperature is falling toward the 2–8°C target; staff are watching the recovery.",
  ],
  [
    "Remote weather station",
    -12,
    74,
    9,
    "Online",
    "Battery has fallen from 60% to 9% overnight. Road access will close tomorrow and no charging source is available until next month.",
  ],
] as const;
