import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowRight,Shuffle,LoaderCircle,Search,X,ChevronLeft,ChevronRight} from 'lucide-react';
import './style.css';
async function api(route,body){const response=await fetch('/api/'+route,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||'Something went wrong.');return data;}
const labels={name:'Name',job_title:'Job title',country:'Country',work_mode:'Works from',description:'A little context',continent:'Continent',capital:'Capital',languages:'Languages',sensor:'Sensor',location:'Location',temperature_c:'Temperature',humidity_pct:'Humidity',battery_pct:'Battery',status:'Status'};
function App(){
 const [dataset,setDataset]=useState(null),[query,setQuery]=useState(''),[result,setResult]=useState(null),[submitted,setSubmitted]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[page,setPage]=useState(0);
 const input=useRef(null);
 useEffect(()=>{api('dataset').then(setDataset).catch(e=>setError(e.message));},[]);
 useEffect(()=>{const handler=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();input.current?.focus();}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);},[]);
 async function generate(){if(busy)return;setBusy('generate');setError('');try{const d=await api('generate',{});setDataset(d);setQuery('');setSubmitted('');setResult(null);setPage(0);}catch(e){setError(e.message);}finally{setBusy('');}}
 async function search(value=query){if(busy||!dataset)return;if(!value.trim()){setResult(null);setSubmitted('');setPage(0);return;}setBusy('search');setQuery(value);setError('');try{const r=await api('search',{query:value,version:dataset.version});setResult(r);setSubmitted(value);setPage(0);}catch(e){setError(e.message);}finally{setBusy('');}}
 function clear(){setQuery('');setSubmitted('');setResult(null);setPage(0);setError('');input.current?.focus();}
 const rows=result?result.results.filter(r=>r.probability>=.7).sort((a,b)=>b.probability-a.probability).map(r=>r.row):dataset?.rows||[];
 const totalPages=Math.max(1,Math.ceil(rows.length/10));
 const columns=dataset?.columns||[];
 return <main>
  <header><a href="/" className="wordmark" aria-label="postgres-Jev home"><span>postgres</span><i>Jev</i><span className="logo-dot">.</span></a><a className="about-link" href="https://docs.typesafe.ai/api" target="_blank" rel="noreferrer">Powered by TypeSafe <ArrowUpRight size={13}/></a></header>
  <section className="intro"><div className="eyebrow"><span/> SQL, WITH A LITTLE INTUITION</div><h1>Skip the syntax.<br/><em>Ask your database.</em></h1><p>Search by what you mean. No embeddings, no index.<br/>Just a table, a question, and <span className="inline-jev">jev()</span>.</p></section>
  <section className="playground" aria-label="Database playground">
   <div className="dataset-bar"><div><span className="table-icon">▦</span><strong>{dataset?.title||'Your database'}</strong><span className="row-count">{dataset?.rows.length??'…'} rows</span></div><button className="generate" onClick={generate} disabled={!!busy||!dataset}>{busy==='generate'?<LoaderCircle size={14} className="spin"/>:<Shuffle size={14}/>}<span>{busy==='generate'?'Generating…':'Generate random database'}</span></button></div>
   <form className="search-form" onSubmit={e=>{e.preventDefault();search();}}><span className="asterisk">✳</span><input ref={input} aria-label="Search your database" placeholder={dataset?.examples[0]?`Try “${dataset.examples[0].toLowerCase()}”`:'Ask a question about these records…'} value={query} onChange={e=>setQuery(e.target.value)} maxLength={500}/>{query&&<button type="button" className="clear" onClick={clear} disabled={!!busy} aria-label="Clear search"><X size={15}/></button>}<button className="search-button" aria-label="Search" disabled={!!busy||!dataset||!query.trim()}>{busy==='search'?<LoaderCircle size={17} className="spin"/>:<ArrowRight size={18}/>}<span>{busy==='search'?'Searching':'Search'}</span><kbd>↵</kbd></button></form>
   <div className="examples"><span>OR TRY</span>{dataset?.examples.slice(0,3).map(q=><button disabled={!!busy} key={q} onClick={()=>search(q)}>{q}<ArrowUpRight size={11}/></button>)}</div>
   {error&&<div className="error" role="alert"><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss error"><X size={15}/></button></div>}
   <div className="table-caption" aria-live="polite"><span>{result?<><strong>{rows.length} matches</strong><span className="caption-query"> for “{submitted}”</span><button disabled={!!busy} onClick={clear}>Show all</button></>:dataset?.note||'Loading the playground…'}</span><span className="mode"><span className="status-dot"/>{dataset?.live?'Jev live':'Demo'}{result&&<> <span className="divider">/</span> {result.elapsed<1?'<1':result.elapsed} ms{result.cached>0?' · cached':''}</>}</span></div>
   <div className={`table-wrap ${busy?'is-busy':''}`} aria-busy={!!busy}><table><thead><tr><th className="index-cell">#</th>{columns.map(c=><th key={c}>{labels[c]||c}</th>)}</tr></thead><tbody>{rows.slice(page*10,page*10+10).map((row,i)=><tr key={row.id??i}><td className="index-cell">{String(page*10+i+1).padStart(2,'0')}</td>{columns.map((c,ci)=><td key={c} className={`${ci===0?'primary-cell':''} ${c==='description'?'description-cell':''}`} title={String(row[c]??'')}>{c==='name'?<><span className={`avatar color-${row.id%5}`}>{row.name.split(' ').map(n=>n[0]).join('')}</span>{row.name}</>:c==='work_mode'||c==='status'?<span className={`badge ${['Remote','Online'].includes(row[c])?'green':''}`}><span/>{row[c]==='Remote'?'Anywhere':row[c]}</span>:c==='temperature_c'?`${row[c]}°C`:['humidity_pct','battery_pct'].includes(c)?`${row[c]}%`:String(row[c]??'—')}</td>)}</tr>)}{!rows.length&&<tr><td className="empty" colSpan={columns.length+1}>{dataset?<><Search size={25}/><strong>No matches this time.</strong><span>Try another question, or generate a fresh database.</span></>:'Loading records…'}</td></tr>}</tbody></table></div>
   <div className="table-footer"><span>{rows.length?page*10+1:0}–{Math.min(page*10+10,rows.length)} of {rows.length} rows</span><div><button aria-label="Previous page" disabled={page===0||!!busy} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={14}/></button><span>{page+1} / {totalPages}</span><button aria-label="Next page" disabled={page>=totalPages-1||!!busy} onClick={()=>setPage(p=>p+1)}><ChevronRight size={14}/></button></div></div>
   <div className="demo-note">{dataset?.live?'Each record is judged by Jev. Matches use a 70% probability cutoff.':'Offline preview · example questions use demo rules. A TypeSafe key enables any question.'}</div>
  </section>
  <footer><span>Not a new query language.<br/><strong>A little understanding for the one you know.</strong></span><code>WHERE <span>jev</span>(row, 'what you mean')</code></footer>
 </main>;
}
createRoot(document.getElementById('root')).render(<App/>);
